export const PRODUCT_TYPES = [
  { id: "laptop", label: "Laptop" },
  { id: "desktop", label: "Desktop" },
  { id: "keyboard", label: "Keyboard" },
  { id: "mouse", label: "Mouse" },
  { id: "monitor", label: "Monitor" },
  { id: "accessory", label: "Accessory" },
  // New product types from hero
  { id: "smartphone", label: "Smartphone" },
  { id: "audio", label: "Audio" },
  { id: "home-electronics", label: "Home Electronics" },
  { id: "wearables", label: "Wearables" },
  { id: "tv", label: "TV" },
];

// Categories per product type
export const PRODUCT_CATEGORIES = {
  laptop: [
    "Ultrabooks",
    "Gaming Laptops",
    "Business Laptops",
    "Budget Laptops",
    "2-in-1 Convertibles",
    "Chromebooks",
    "Workstation Laptops",
    "Student Laptops",
    "Creative/Design Laptops",
    "Thin and Light Laptops",
    "MacBooks",
    "Gaming Ultrabooks",
    "Rugged Laptops",
    "Netbooks",
    "Refurbished Laptops",
  ],
  desktop: ["Gaming Desktops", "Workstation PCs", "All-in-One PCs", "Mini PCs"],
  keyboard: [
    "Mechanical Keyboards",
    "Membrane Keyboards",
    "Wireless Keyboards",
    "Gaming Keyboards",
  ],
  mouse: ["Gaming Mice", "Wireless Mice", "Ergonomic Mice", "Trackballs"],
  monitor: ["Gaming Monitors", "Professional Monitors", "Portable Monitors"],
  accessory: ["Cables & Adapters", "Headsets", "Webcams", "Speakers"],
  // New categories from hero data
  smartphone: [
    "Flagship Phones",
    "Mid-range Phones",
    "Budget Phones",
    "Gaming Phones",
    "Camera Phones",
    "Foldable Phones",
    "Business Phones",
    "Refurbished Phones",
    "5G Phones",
    "Compact Phones",
  ],
  audio: [
    "Wireless Earbuds",
    "Headphones",
    "Speakers",
    "Soundbars",
    "Earphones",
    "Gaming Headsets",
    "Noise Cancelling Headphones",
    "Sports Earphones",
    "Bluetooth Speakers",
    "Home Audio Systems",
  ],
  "home-electronics" : [
    "Smart Home Devices",
    "Smart TVs",
    "Streaming Devices",
    "Home Security",
    "Smart Lighting",
    "Robot Vacuums",
    "Smart Plugs",
    "Voice Assistants",
    "Home Theater Systems",
    "Gaming Consoles",
  ],
  wearables: [
    "Smart Watches",
    "Fitness Trackers",
    "Smart Glasses",
    "Health Monitors",
    "Sports Watches",
    "Luxury Smartwatches",
    "Kids Smartwatches",
  ],
  tv: [
    "4K TVs",
    "8K TVs",
    "Smart TVs",
    "OLED TVs",
    "QLED TVs",
    "Gaming TVs",
    "Curved TVs",
    "Portable TVs",
    "Home Theater Projectors",
  ],
};

export const PRODUCT_STATUS = [
  "Brand New",
  "Refurbished",
  "Used-Like New",
  "Used-Good",
  "Used-Fair",
];

export const STOCK_STATUS = [
  "Archived",
  "Out of Stock",
  "In Stock",
  "Low Stock",
  "Preorder",
  "Discontinued",
  "Backordered",
  "Limited Stock",
  "Available Soon",
  "Temporarily Unavailable",
  "Coming Soon",
  "Special Order",
  "In Transit",
  "On Hold",
  "Reserved",
  "For Parts or Not Working",
];


